version: '2'
services:
  verdaccio:
    container_name: npm-mirror-v1 
    restart: always
    image: verdaccio/verdaccio
    ports:
      - 4873:4873
    volumes:
      - ./conf/:/verdaccio/conf
      - ./storage/:/verdaccio/storage
      - ./local_storage/:/verdaccio/storage